---
abstract: 'A simple JSON explorer for the command line (think ls for JSON)'
author:
  - 'Alfie John <alfiej@opera.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: jsonexplorer.pl
no_index:
  directory:
    - t
    - inc
requires:
  Data::Format::Pretty::JSON: 0
  Getopt::Long: 0
  Pod::Usage: 0
version: v1.0.0
